name: noname_demo
description: "A new Flutter project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.2
  dio: ^5.4.0
  flutter:
    sdk: flutter


  flutter_bloc: ^8.1.3
  go_router: ^12.1.3
  keframe: ^3.0.0
  logging: ^1.2.0
  meta: ^1.10.0
  path: ^1.8.3
  pure: ^0.2.0
  sliver_tools: ^0.2.12
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
